# Build documentation of ReadTheDocs

name: Document on ReadTheDocs

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  document:
    name: Documentation build on ReadTheDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - uses: ammaraskar/sphinx-action@master"
        with:
          docs-folder: "docs/"